packages:
  - "packages/*"
  - "apps/*"
catalog:
  "@babel/core": 7.29.7
  "@babel/preset-env": 7.29.0
  "@babel/runtime": 7.29.7
  "@react-native-harness/platform-android": 1.3.0
  "@react-native-harness/platform-apple": 1.3.0
  "@rnx-kit/metro-config": 2.2.4
  "@rock-js/platform-android": 0.15.0
  "@rock-js/platform-ios": 0.15.0
  "@rock-js/plugin-metro": 0.15.0
  "@rock-js/provider-github": 0.15.0
  eslint: 8.57.1
  jest: 30.2.0
  prettier: 2.8.8
  react-native-harness: 1.3.0
  react-native-safe-area-context: 5.8.0
  react-native-test-app: 5.4.5
  rock: 0.15.0
  typescript: 5.9.3
catalogs:
  rn82:
    "@react-native-community/cli": 20.0.0
    "@react-native-community/cli-platform-android": 20.0.0
    "@react-native-community/cli-platform-ios": 20.0.0
    "@react-native/babel-preset": 0.82.1
    "@react-native/eslint-config": 0.82.1
    "@react-native/metro-config": 0.82.1
    "@react-native/new-app-screen": 0.82.1
    "@react-native/typescript-config": 0.82.1
    "@types/react": 19.1.17
    react: 19.1.1
    react-native: 0.82.1
  rn83:
    "@react-native-community/cli": 20.0.0
    "@react-native-community/cli-platform-android": 20.0.0
    "@react-native-community/cli-platform-ios": 20.0.0
    "@react-native/babel-preset": 0.83.10
    "@react-native/eslint-config": 0.83.10
    "@react-native/metro-config": 0.83.10
    "@react-native/new-app-screen": 0.83.10
    "@react-native/typescript-config": 0.83.10
    "@types/react": 19.2.17
    react: 19.2.0
    react-native: 0.83.10
  rn84:
    "@react-native-community/cli": 20.1.0
    "@react-native-community/cli-platform-android": 20.1.0
    "@react-native-community/cli-platform-ios": 20.1.0
    "@react-native/babel-preset": 0.84.1
    "@react-native/eslint-config": 0.84.1
    "@react-native/metro-config": 0.84.1
    "@react-native/new-app-screen": 0.84.1
    "@react-native/typescript-config": 0.84.1
    "@types/react": 19.2.17
    react: 19.2.3
    react-native: 0.84.1
  rn85:
    "@react-native-community/cli": 20.1.0
    "@react-native-community/cli-platform-android": 20.1.0
    "@react-native-community/cli-platform-ios": 20.1.0
    "@react-native/babel-preset": 0.85.3
    "@react-native/eslint-config": 0.85.3
    "@react-native/metro-config": 0.85.3
    "@react-native/new-app-screen": 0.85.3
    "@react-native/typescript-config": 0.85.3
    "@types/react": 19.2.17
    react: 19.2.3
    react-native: 0.85.3
  rn86:
    "@react-native-community/cli": 20.1.0
    "@react-native-community/cli-platform-android": 20.1.0
    "@react-native-community/cli-platform-ios": 20.1.0
    "@react-native/babel-preset": 0.86.0
    "@react-native/eslint-config": 0.86.0
    "@react-native/metro-config": 0.86.0
    "@react-native/new-app-screen": 0.86.0
    "@react-native/typescript-config": 0.86.0
    "@types/react": 19.2.17
    react: 19.2.3
    react-native: 0.86.0
allowBuilds:
  esbuild: true
  unrs-resolver: true
