ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until
  File.exist?("#{ws_dir}/node_modules/react-native-test-app/test_app.rb") ||
  ws_dir.expand_path.to_s == '/'
require "#{ws_dir}/node_modules/react-native-test-app/test_app.rb"
require_relative '../../harness-shared/cocoapods_pathname_workaround'

workspace 'SurrealDbHarnessRN86.xcworkspace'

use_test_app! :hermes_enabled => true, :fabric_enabled => true
