// Generated by uniffi-bindgen-react-native
#include "react-native-surrealdb.h"
#include "generated/surrealdb_rn_core.hpp"

namespace surrealdb {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeSurrealdbRnCore::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}