// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-surrealdb.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "SurrealDbRnSpec.h"

@interface Surrealdb : NSObject <NativeSurrealdbSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Surrealdb : NSObject <RCTBridgeModule>
#endif

@end