---
rust:
  directory: ../..
  manifestPath: crates/surrealdb-rn-core/Cargo.toml

bindings:
  cpp: cpp/generated
  ts: src/generated

turboModule:
  entrypoint: src/native.tsx

android:
  apiLevel: 24
  targets:
    - arm64-v8a
    - armeabi-v7a
    - x86_64
    - x86
  useSharedLibrary: false

ios:
  frameworkName: SurrealDbRnFramework
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios

noOverwrite:
  - android/build.gradle
  - android/CMakeLists.txt
